import Header from '@/components/shared/MainComponent/Header/header';
import { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = { title: "Next | Оформление заказа", description: "Generated by create next app" };

export default function CheckoutLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang='en'>
            <body>
                <main className='bg-slate-50'>
                    <Header />
                    {children}
                </main>
            </body>
        </html>
    );
};
