import React from "react";
import "../globals.css";
import  { Toaster } from 'react-hot-toast';
import Header from "@/src/components/shared/Header/header";
import type { Metadata } from "next";

export const metadata: Metadata = { title: "Next | Main", description: "Generated by create next app" };


export default function HomeLayout({children}
  : Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body>
        <main>
          <Header/>
          {children}
          <Toaster/>
        </main>
      </body>
    </html>
  );
}
